#!/bin/bash
set -e

apt-get update

apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    python-dev \
    python-pip \
    git

easy_install -U pip

pip install -r hooks/python-pkgs.txt
