#!/bin/bash

set +e
status-set maintenance "Installing predependencies"

set -e

apt-get update

apt-get install -y \
    python-dev \
    python-pip \
    git

easy_install -U pip

pip install -r hooks/python-pkgs.txt
