#!/usr/bin/env python

import argparse
from docker import Client
import sys

parser = argparse.ArgumentParser(description="Fetch information about container environment")
parser.add_argument('--network', help="Return IP of running image", action="store_true")
parser.add_argument('-i', help="Name of docker image to check for", required=True)


c = Client(base_url='unix://var/run/docker.sock', version='auto')

def search_container(name):
    containers = c.containers()
    for ctr in containers:
       if name in ctr['Image']:
	 return ctr['Id']

def container_ip(container_id):
    container_data = c.inspect_container(container_id)
    return container_data['NetworkSettings']['IPAddress']

if __name__ == "__main__":

    args = parser.parse_args()
    if args.network:
        container_id = search_container(args.i)
        if container_id is not None:
            print container_ip(container_id)
