- hosts: all
  tasks:
    - name: install or upgrade
      include: install-or-upgrade.yaml
      tags:
        - install
        - upgrade-charm

    - name: config changed
      include: config-changed.yaml
      tags:
        - config-changed
